// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjM2gSNDCVr12bn1zYVK5f_2dtmLEwPBc',
    appId: '1:476663108768:web:f95ea2e6a5cc437ee525c5',
    messagingSenderId: '476663108768',
    projectId: 'fir-chat-660cd',
    authDomain: 'fir-chat-660cd.firebaseapp.com',
    storageBucket: 'fir-chat-660cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmo3Dhs_glDLJsFYYjex8hhyZGBhIpC8s',
    appId: '1:476663108768:android:355b4645f7d11b35e525c5',
    messagingSenderId: '476663108768',
    projectId: 'fir-chat-660cd',
    storageBucket: 'fir-chat-660cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUtC4mvMRcdD-qQfoMkMU9-pxQ6Y09G5I',
    appId: '1:476663108768:ios:fc3b7015507887eae525c5',
    messagingSenderId: '476663108768',
    projectId: 'fir-chat-660cd',
    storageBucket: 'fir-chat-660cd.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUtC4mvMRcdD-qQfoMkMU9-pxQ6Y09G5I',
    appId: '1:476663108768:ios:71e0580ee5fc6a05e525c5',
    messagingSenderId: '476663108768',
    projectId: 'fir-chat-660cd',
    storageBucket: 'fir-chat-660cd.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
