// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmADfHoTkZOQXZH2_91RnIEgn1wrURoEI',
    appId: '1:81872217996:web:391324a0014128468a18a9',
    messagingSenderId: '81872217996',
    projectId: 'chatapptute-55209',
    authDomain: 'chatapptute-55209.firebaseapp.com',
    storageBucket: 'chatapptute-55209.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiUVmMC-vlJLGUqH_xX4FtL1CE4Lfeq-4',
    appId: '1:81872217996:android:0e6d8b531d8bca3d8a18a9',
    messagingSenderId: '81872217996',
    projectId: 'chatapptute-55209',
    storageBucket: 'chatapptute-55209.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCtWcJwAbcqAxe5LOgdFmNoTGIRahuy18',
    appId: '1:81872217996:ios:baf19deb90aa94fa8a18a9',
    messagingSenderId: '81872217996',
    projectId: 'chatapptute-55209',
    storageBucket: 'chatapptute-55209.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCtWcJwAbcqAxe5LOgdFmNoTGIRahuy18',
    appId: '1:81872217996:ios:47ff3e38729a0ed08a18a9',
    messagingSenderId: '81872217996',
    projectId: 'chatapptute-55209',
    storageBucket: 'chatapptute-55209.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
